#-------------------------------
# Site Settings
title: Lukas Ruzicka
logo: # You can add own logo. For example '/images/logo.png'.
description: My personal portfolio website.
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About me'
      url: '/about/'
    - title: 'My career'
      url: '/career/'
    - title: 'Tech Stack'
      url: '/techstack/'
    - title: 'References'
      submenu:
      - url: '/work/'
        title: 'Works'
      - url: '/own/'
        title: 'Own projects'
    - title: 'Articles'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Author Settings
author:
  author__name: Lukas Ruzicka
  author__bio: iOS engineer üçè, living in Prague, Czech Republic üá®üáø
  author__avatar: '/images/portraits/megu-head-square.jpg'

social:
- {icon: "ion-logo-github", link: "https://github.com/lukas-ruzicka"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/lruzicka96/"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/ruzickalukas96/"}
- {icon: "ion-logo-twitter", link: "https://twitter.com/ruzickalukas96"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Lukas Ruzicka, the iOS engineer 
  hero__description: "I'm Lukas, an **iOS engineer** üçè, living in **Prague, Czech Republic** üá®üáø. I'm grateful to be able to use my **creative skills** to contribute to **making the world a better place** ‚ú®. Being around people who are **passionate** about their daily work and **want to make an impact** is something **I love most** about this industry üíú."
  hero__image: "/images/portraits/studio-portrait-cropped.jpg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: Companies I've had the pleasure to work with

logo__items:
  - name: endavu
    link: "https://www.endavu.com"
    image: "/images/companies/endavu.svg"
  
  - name: MeguMethod
    link: "https://www.megumethod.com/"
    image: "/images/companies/megumethod.svg"

  - name: tado¬∞
    link: "https://www.tado.com/"
    image: "/images/companies/tado.svg"

  - name: Synetech
    link: "https://synetech.cz/"
    image: "/images/companies/synetech.svg"

  - name: SpaceKnow
    link: "https://spaceknow.com/"
    image: "/images/companies/spaceknow.svg"


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: References
  work__description: Some of the interesting projects and other initiatives I have worked on over the years.

#-------------------------------
# Own projects Settings
own:
  enable: true
  own__title: Own projects
  own__description: Here are the projects I've done on my own.


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title: Recommendations
testimonial__description: 

testimonial__items:
  - name: "Daniel Rutkovsky"
    image: "/images/recommendations/daniel-rutkovsky.jpg"
    designation: "CTO & Co-Founder at MeguMethod"
    link: "https://www.linkedin.com/in/daniel-rutkovsky/"
    content: "I've started working with Lukas almost 5 years ago. He came as a skilled medior to our team. He worked on many projects and his skills grew blazingly fast. He soon started leading our projects and focusing on AR development."
    content_second_paragraph: "As he became senior developer Lukas took on more responsibilities and led our iOS team (house in our jargon) for the last two years. During this time his team grew and became the best-managed team in our company."
    content_third_paragraph: "Not only that Lukas has great management skills, he's also an excellent developer. He was our iOS tech guru and author of many internal libraries and architecture patterns, that we use on our projects today. He has deep knowledge of Clean architecture, SPM (swift package manager) and SwiftUI."

  - name: "Tomas Novotny"
    image: "/images/recommendations/tomas-novotny.jpg"
    designation: "iOS Tech Lead at SYNETECH"
    link: "https://www.linkedin.com/in/tom-nvt/"
    content: "From the beginning of our cooperation about 4 years ago, Luk√°≈° was one of the most helpful and supportive colleagues on the team. He guided me in my first steps in Synetech and also in Synetech's biggest project, on which we worked together. It was an honor to work with Luk√°≈° and see him grow in both technical and soft skills. He is always open to finding out ways to improve himself as well as the well-being of the whole team. Besides being a great iOS engineer, who is able to cope with any technical challenge, he is also experienced in managerial roles as he can find the balance between the needs of the company and the iOS team and be a great delegate for the team."

  - name: "Niklas Astrom"
    image: "/images/recommendations/niklas-astrom.jpg"
    designation: "Engineering Manager at tado¬∞"
    link: "https://www.linkedin.com/in/niklasastrom/"
    content: "Luk√°≈°‚Äô knowledge and skills as well as willingness to help makes me happy I got the chance to work together with him! During the year we worked together, he not only delivered high quality software, but he was also always there to help others with everything from pair programming to discussing technical solutions and team improvements. He is a strong team player and someone I could trust and count on. I'm happy that I got to know him, and I'm sure he will do great in his upcoming adventures!"

#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Articles
  blog__description: I'm not a blogger, but here you can find a few things I thought deserved to be written down.


#-------------------------------
# Footer Settings
footer__background__image: "/images/footer-bg.jpg"


#-------------------------------
# Contact Settings
contact:
  email: xqkjyrbe # Formspree (https://formspree.io/) form id
  description: Any questions about anything I've been working on? Do you have a project that you think I might like and could possibly be involved in? Let me know!


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: G-0LJ5CLHSWF